title: WebGestaltR
description: WebGestaltR Documentation
theme: just-the-docs

url: https://iblacksand.github.io/WebGestaltR
logo: "/assets/logo.svg"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/iblacksand/WebGestaltR" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

aux_links:
  Repository: https://github.com/iblacksand/WebGestaltR

callouts:
  note:
    title: note
    color: blue
