title: WebGestaltR
description: WebGestaltR Documentation
theme: just-the-docs

url: https://iblacksand.github.io/WebGestaltR

aux_links:
  Template Repository: https://github.com/iblacksand/WebGestaltR
